sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zxcvbnm123

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: LTAI5tGdNNL3H2g8TU7ic2r7
    access-key-secret: KeOk2pD2GMhdQEbAGRJhyhnEYSuso1
    bucket-name: webdemo1

  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 1

  wechat:
    appid: wx9e6fad39c1b046a0
    secret: a833b7e71891dc552656a30620797e9c

